rules = [OrganizeImports, RemoveUnused]

OrganizeImports {
  blankLines = Auto
  expandRelative = true
  groupedImports = AggressiveMerge
  coalesceToWildcardImportThreshold = 5
  groups = [
    "re:javax?\\."
    "scala."
    "zio."
    "zio.http."
    "*"
  ]
}

RemoveUnused {
  imports = false # handled by OrganizeImports
}
